services:
  commander-container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/commander
    working_dir: /commander
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    entrypoint:
      - yarn
    command:
      - start
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:14.5
    container_name: commander-data
    volumes:
      - commander-data:/var/lib/postgresql/data
    ports:
      - 4006:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  commander-data:
    external: true

